/* Blessed Group — site content (from project docs). window.BGData */
window.BGData = {
  company: {
    name: 'Blessed Group',
    email: 'gerencia@blessedgroup.com.py',
    phone: '+595 21 123 4567',
    phoneHref: '+59521123457',
    whatsapp: '595984000000',
    whatsappLabel: '+595 984 000 000',
    address: 'Asunción, Paraguay',
    addressLine: 'Asunción, Paraguay',
    instagram: 'https://www.instagram.com/_blessedgroup/',
    tagline: 'Excelencia en diseño arquitectónico y construcción en Paraguay.',
  },
  nav: [
    { label: 'Inicio', href: '#inicio' },
    { label: 'Nosotros', href: '#nosotros' },
    { label: 'Servicios', href: '#servicios' },
    { label: 'Proceso', href: '#proceso' },
    { label: 'Proyectos', href: '#proyectos' },
    { label: 'Blog', href: '#blog' },
    { label: 'Contacto', href: '#contacto' },
  ],
  hero: [
    {
      eyebrow: 'Blessed Group · Paraguay',
      title: 'Construyendo el futuro',
      subtitle: 'Excelencia en diseño arquitectónico y construcción.',
      text: 'Transformamos tus ideas en proyectos de calidad superior.',
      image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1920&auto=format&fit=crop',
    },
    {
      eyebrow: 'Más de 15 años de experiencia',
      title: 'Solidez, calidad y confianza',
      subtitle: 'Estructuras duraderas que cumplen los más altos estándares.',
      text: 'Nuestra experiencia y méritos nos respaldan en cada obra.',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1920&auto=format&fit=crop',
    },
    {
      eyebrow: 'Soluciones integrales',
      title: 'Del concepto a la entrega',
      subtitle: 'Acompañamos cada etapa de tu obra con un equipo experto.',
      text: 'Diseño, ingeniería, presupuesto y ejecución en un solo lugar.',
      image: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=1920&auto=format&fit=crop',
    },
  ],
  about: {
    eyebrow: 'Sobre nosotros',
    title: 'Blessed Group se ha consolidado como referente en diseño y construcción en Paraguay.',
    body: 'Ofrecemos soluciones integrales para todas las etapas de la construcción de una obra: desde el diseño conceptual, la arquitectura y la ingeniería, hasta el proyecto ejecutivo, la estimación del presupuesto y la supervisión de obra. Transformamos cada idea en espacios funcionales, seguros y de calidad superior.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
    floatValue: '85.000+',
    floatLabel: 'M² construidos',
    features: [
      { icon: 'ShieldCheck', label: 'Calidad garantizada' },
      { icon: 'Users', label: 'Equipo experto' },
      { icon: 'Compass', label: 'Soluciones a medida' },
      { icon: 'ClipboardCheck', label: 'Cumplimiento de plazos' },
    ],
  },
  stats: [
    { icon: 'Award', value: 15, suffix: '+', label: 'Años de experiencia' },
    { icon: 'Building2', value: 120, suffix: '+', label: 'Proyectos completados' },
    { icon: 'Users', value: 50, suffix: '+', label: 'Clientes satisfechos' },
    { icon: 'Ruler', value: 85000, suffix: '+', label: 'M² construidos' },
  ],
  services: [
    { icon: 'PenTool', title: 'Diseño Arquitectónico', desc: 'Creamos espacios funcionales y estéticos que se adaptan a tus necesidades y superan tus expectativas.' },
    { icon: 'HardHat', title: 'Construcción', desc: 'Ejecutamos tus proyectos con calidad y eficiencia, con materiales de primera línea y mano de obra calificada.' },
    { icon: 'Building2', title: 'Obras Civiles', desc: 'Desarrollamos infraestructura sólida y duradera cumpliendo los más altos estándares de la industria.' },
    { icon: 'Hammer', title: 'Remodelación', desc: 'Renovamos y transformamos espacios existentes, dándoles nueva vida, valor y funcionalidad.' },
    { icon: 'ClipboardCheck', title: 'Supervisión de Obra', desc: 'Monitoreamos cada etapa de la obra garantizando calidad, plazos y cumplimiento de las normas.' },
    { icon: 'Compass', title: 'Consultoría', desc: 'Te asesoramos en la viabilidad técnica, económica y legal de tu proyecto desde el primer día.' },
  ],
  process: [
    { icon: 'Compass', step: '01', title: 'Diseño conceptual', desc: 'Definimos la visión, el alcance y los objetivos del proyecto junto a vos.' },
    { icon: 'FileText', step: '02', title: 'Proyecto ejecutivo', desc: 'Desarrollamos planos, ingeniería y especificaciones con metodología BIM.' },
    { icon: 'Layers', step: '03', title: 'Cómputo y presupuesto', desc: 'Elaboramos un presupuesto detallado y transparente, optimizando recursos.' },
    { icon: 'ShieldCheck', step: '04', title: 'Habilitaciones y permisos', desc: 'Gestionamos todos los trámites y permisos necesarios para iniciar la obra.' },
    { icon: 'HardHat', step: '05', title: 'Ejecución de obra', desc: 'Construimos con un equipo calificado y control de calidad permanente.' },
    { icon: 'ClipboardCheck', step: '06', title: 'Entrega y seguimiento', desc: 'Entregamos en plazo y acompañamos con seguimiento posterior a la obra.' },
  ],
  projects: [
    { category: 'Comercial', title: 'Edificios Comerciales', count: '25 proyectos', image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=900&auto=format&fit=crop' },
    { category: 'Residencial', title: 'Viviendas Residenciales', count: '32 proyectos', image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=900&auto=format&fit=crop' },
    { category: 'Industrial', title: 'Plantas Industriales', count: '18 proyectos', image: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?q=80&w=900&auto=format&fit=crop' },
    { category: 'Remodelación', title: 'Remodelaciones', count: '20 proyectos', image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=900&auto=format&fit=crop' },
  ],
  blog: [
    { date: '01 Abr 2025', category: 'Seguridad', title: 'Buenas prácticas de seguridad en la construcción industrial', excerpt: 'La construcción industrial conlleva riesgos. Con normas y buenas prácticas es posible minimizarlos y garantizar un entorno laboral seguro.', image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=900&auto=format&fit=crop' },
    { date: '25 Mar 2026', category: 'Planificación', title: 'Construir bien comienza mucho antes de iniciar la obra', excerpt: 'En proyectos de gran envergadura, la planificación no es una etapa inicial: es un proceso estratégico continuo que define el éxito.', image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=900&auto=format&fit=crop' },
    { date: '01 Abr 2025', category: 'Materiales', title: 'Consejos prácticos para elegir el aislamiento adecuado', excerpt: 'El aislamiento correcto mejora el confort y la eficiencia. Te compartimos consejos prácticos para elegir el adecuado en cada proyecto.', image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=900&auto=format&fit=crop' },
  ],
};
